# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\FileBox\Code\Python\PasswordManager\py-passwordmanager\gui\AddItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(580, 460)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(580, 460))
        Dialog.setMaximumSize(QtCore.QSize(580, 460))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mainui/icon/MainIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 9, 0, 1, 1)
        self.le_name = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.le_name.setFont(font)
        self.le_name.setStyleSheet("QLineEdit\n"
"{\n"
"    border-style:none;\n"
"    padding:6px;\n"
"    border-radius:15px;\n"
"    border:2px solid #DCE4EC;\n"
"}\n"
"QLineEdit:focus\n"
"{\n"
"    border:2px solid #34495E;\n"
"}")
        self.le_name.setMaxLength(256)
        self.le_name.setAlignment(QtCore.Qt.AlignCenter)
        self.le_name.setClearButtonEnabled(True)
        self.le_name.setObjectName("le_name")
        self.gridLayout.addWidget(self.le_name, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(80, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 8, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.le_account = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.le_account.setFont(font)
        self.le_account.setStyleSheet("QLineEdit\n"
"{\n"
"    border-style:none;\n"
"    padding:6px;\n"
"    border-radius:15px;\n"
"    border:2px solid #DCE4EC;\n"
"}\n"
"QLineEdit:focus\n"
"{\n"
"    border:2px solid #34495E;\n"
"}")
        self.le_account.setMaxLength(256)
        self.le_account.setAlignment(QtCore.Qt.AlignCenter)
        self.le_account.setClearButtonEnabled(True)
        self.le_account.setObjectName("le_account")
        self.gridLayout.addWidget(self.le_account, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 0, 1, 1)
        self.lb_name_warning = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_name_warning.sizePolicy().hasHeightForWidth())
        self.lb_name_warning.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.lb_name_warning.setFont(font)
        self.lb_name_warning.setStyleSheet("QLabel\n"
"{\n"
"    color:rgb(255, 0, 0);\n"
"}")
        self.lb_name_warning.setTextFormat(QtCore.Qt.PlainText)
        self.lb_name_warning.setObjectName("lb_name_warning")
        self.gridLayout.addWidget(self.lb_name_warning, 1, 2, 1, 1)
        self.le_password = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.le_password.setFont(font)
        self.le_password.setStyleSheet("QLineEdit\n"
"{\n"
"    border-style:none;\n"
"    padding:6px;\n"
"    border-radius:15px;\n"
"    border:2px solid #DCE4EC;\n"
"}\n"
"QLineEdit:focus\n"
"{\n"
"    border:2px solid #34495E;\n"
"}")
        self.le_password.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly|QtCore.Qt.ImhLatinOnly|QtCore.Qt.ImhUrlCharactersOnly)
        self.le_password.setMaxLength(256)
        self.le_password.setAlignment(QtCore.Qt.AlignCenter)
        self.le_password.setClearButtonEnabled(True)
        self.le_password.setObjectName("le_password")
        self.gridLayout.addWidget(self.le_password, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(50, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 10, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pbt_add = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbt_add.setFont(font)
        self.pbt_add.setStyleSheet("QPushButton {\n"
"    border-style:none;\n"
"    padding:10px;\n"
"    border-radius:15px;\n"
"    color:#FFFFFF;\n"
"    background:#34495E;\n"
"}\n"
"QPushButton:hover {\n"
"    color:#4E6D8C;\n"
"    background:#e5e5e5;\n"
"    border:2px solid #34495E;\n"
"}\n"
"QPushButton:pressed {\n"
"    color:#000000;\n"
"    background:#B8C6D1;\n"
"}\n"
"QPushButton:disabled{\n"
"    background:rgb(134, 134, 134);\n"
"    border-color:rgb(134, 134, 134);\n"
"}")
        self.pbt_add.setFlat(True)
        self.pbt_add.setObjectName("pbt_add")
        self.gridLayout_2.addWidget(self.pbt_add, 1, 1, 1, 1)
        self.pbt_cancel = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbt_cancel.setFont(font)
        self.pbt_cancel.setStyleSheet("QPushButton {\n"
"    border-style:none;\n"
"    padding:10px;\n"
"    border-radius:15px;\n"
"    color:#FFFFFF;\n"
"    background:#34495E;\n"
"}\n"
"QPushButton:hover {\n"
"    color:#4E6D8C;\n"
"    background:#e5e5e5;\n"
"    border:2px solid #34495E;\n"
"}\n"
"QPushButton:pressed {\n"
"    color:#000000;\n"
"    background:#B8C6D1;\n"
"}\n"
"")
        self.pbt_cancel.setFlat(True)
        self.pbt_cancel.setObjectName("pbt_cancel")
        self.gridLayout_2.addWidget(self.pbt_cancel, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 9, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 4, 1, 1, 1)
        self.te_note = QtWidgets.QTextEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.te_note.setFont(font)
        self.te_note.setStyleSheet("QTextEdit\n"
"{\n"
"    border-style:none;\n"
"    padding:4px;\n"
"    border-radius:5px;\n"
"    border:2px solid #DCE4EC;\n"
"}\n"
"QTextEdit:focus\n"
"{\n"
"    border:2px solid #34495E;\n"
"}")
        self.te_note.setObjectName("te_note")
        self.gridLayout.addWidget(self.te_note, 9, 1, 1, 1)
        self.lb_account_warning = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_account_warning.sizePolicy().hasHeightForWidth())
        self.lb_account_warning.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.lb_account_warning.setFont(font)
        self.lb_account_warning.setStyleSheet("QLabel\n"
"{\n"
"    color:rgb(255, 0, 0);\n"
"}")
        self.lb_account_warning.setObjectName("lb_account_warning")
        self.gridLayout.addWidget(self.lb_account_warning, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 8, 2, 1, 1)
        self.le_email_or_phone = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.le_email_or_phone.setFont(font)
        self.le_email_or_phone.setStyleSheet("QLineEdit\n"
"{\n"
"    border-style:none;\n"
"    padding:6px;\n"
"    border-radius:15px;\n"
"    border:2px solid #DCE4EC;\n"
"}\n"
"QLineEdit:focus\n"
"{\n"
"    border:2px solid #34495E;\n"
"}")
        self.le_email_or_phone.setMaxLength(256)
        self.le_email_or_phone.setAlignment(QtCore.Qt.AlignCenter)
        self.le_email_or_phone.setClearButtonEnabled(True)
        self.le_email_or_phone.setObjectName("le_email_or_phone")
        self.gridLayout.addWidget(self.le_email_or_phone, 7, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 160, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setStyleSheet("QLabel\n"
"{\n"
"    color:rgb(255, 0, 0);\n"
"}")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.pbt_gen = QtWidgets.QPushButton(Dialog)
        self.pbt_gen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pbt_gen.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    image: url(:/mainui/icon/gen2.png);\n"
"}\n"
"QPushButton:hover {\n"
"    image: url(:/mainui/icon/gen1.png);\n"
"}")
        self.pbt_gen.setText("")
        self.pbt_gen.setFlat(True)
        self.pbt_gen.setObjectName("pbt_gen")
        self.horizontalLayout.addWidget(self.pbt_gen)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.le_name, self.le_account)
        Dialog.setTabOrder(self.le_account, self.le_password)
        Dialog.setTabOrder(self.le_password, self.le_email_or_phone)
        Dialog.setTabOrder(self.le_email_or_phone, self.te_note)
        Dialog.setTabOrder(self.te_note, self.pbt_cancel)
        Dialog.setTabOrder(self.pbt_cancel, self.pbt_add)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "添加密码"))
        self.label.setText(_translate("Dialog", "备注"))
        self.label_2.setText(_translate("Dialog", "邮箱/电话"))
        self.lb_name_warning.setToolTip(_translate("Dialog", "名称 为必填项"))
        self.lb_name_warning.setText(_translate("Dialog", "*"))
        self.label_3.setText(_translate("Dialog", "密码"))
        self.pbt_add.setText(_translate("Dialog", "添加"))
        self.pbt_add.setShortcut(_translate("Dialog", "Enter"))
        self.pbt_cancel.setText(_translate("Dialog", "取消"))
        self.label_4.setText(_translate("Dialog", "账号"))
        self.lb_account_warning.setToolTip(_translate("Dialog", "账号 为必填项"))
        self.lb_account_warning.setText(_translate("Dialog", "*"))
        self.label_5.setText(_translate("Dialog", "名称"))
        self.label_6.setToolTip(_translate("Dialog", "密码 为必填项"))
        self.label_6.setText(_translate("Dialog", "*"))
        self.pbt_gen.setToolTip(_translate("Dialog", "生成密码"))
import gui.src.icons_rc
