# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\FileBox\Code\Python\PasswordManager\py-passwordmanager\gui\GenPasswordUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GenPassword(object):
    def setupUi(self, GenPassword):
        GenPassword.setObjectName("GenPassword")
        GenPassword.resize(400, 400)
        GenPassword.setMinimumSize(QtCore.QSize(400, 400))
        GenPassword.setMaximumSize(QtCore.QSize(410, 432))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mainui/icon/MainIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GenPassword.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(GenPassword)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(40, 10, 80, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cbx_uppercase = QtWidgets.QCheckBox(GenPassword)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.cbx_uppercase.setFont(font)
        self.cbx_uppercase.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbx_uppercase.setStyleSheet("QCheckBox {\n"
"    padding: 2px;margin: 2px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:2px;\n"
"    border-color:#34495E;\n"
"      background-color:rgb(255,255,255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:2px;\n"
"    border-color:#0078d7; \n"
"    image: url(:/mainui/icon/selected.png);\n"
"}\n"
"QCheckBox::indicator:hover{\n"
"    border-color:#0078d7; \n"
"}\n"
"QCheckBox:hover {\n"
"    color:rgb(0, 0, 216);\n"
"    padding: 3px;\n"
"}")
        self.cbx_uppercase.setTristate(False)
        self.cbx_uppercase.setObjectName("cbx_uppercase")
        self.verticalLayout_3.addWidget(self.cbx_uppercase)
        self.cbx_lowercase = QtWidgets.QCheckBox(GenPassword)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.cbx_lowercase.setFont(font)
        self.cbx_lowercase.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbx_lowercase.setStyleSheet("QCheckBox {\n"
"    padding: 2px;margin: 2px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:2px;\n"
"    border-color:#34495E;\n"
"      background-color:rgb(255,255,255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:2px;\n"
"    border-color:#0078d7; \n"
"    image: url(:/mainui/icon/selected.png);\n"
"}\n"
"QCheckBox::indicator:hover{\n"
"    border-color:#0078d7; \n"
"}\n"
"QCheckBox:hover {\n"
"    color:rgb(0, 0, 216);\n"
"    padding: 3px;\n"
"}")
        self.cbx_lowercase.setChecked(True)
        self.cbx_lowercase.setObjectName("cbx_lowercase")
        self.verticalLayout_3.addWidget(self.cbx_lowercase)
        self.cbx_digital = QtWidgets.QCheckBox(GenPassword)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.cbx_digital.setFont(font)
        self.cbx_digital.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbx_digital.setStyleSheet("QCheckBox {\n"
"    padding: 2px;margin: 2px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:2px;\n"
"    border-color:#34495E;\n"
"      background-color:rgb(255,255,255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:2px;\n"
"    border-color:#0078d7; \n"
"    image: url(:/mainui/icon/selected.png);\n"
"}\n"
"QCheckBox::indicator:hover{\n"
"    border-color:#0078d7; \n"
"}\n"
"QCheckBox:hover {\n"
"    color:rgb(0, 0, 216);\n"
"    padding: 3px;\n"
"}")
        self.cbx_digital.setChecked(True)
        self.cbx_digital.setObjectName("cbx_digital")
        self.verticalLayout_3.addWidget(self.cbx_digital)
        self.cbx_char = QtWidgets.QCheckBox(GenPassword)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.cbx_char.setFont(font)
        self.cbx_char.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbx_char.setStyleSheet("QCheckBox {\n"
"    padding: 2px;margin: 2px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:2px;\n"
"    border-color:#34495E;\n"
"      background-color:rgb(255,255,255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:2px;\n"
"    border-color:#0078d7; \n"
"    image: url(:/mainui/icon/selected.png);\n"
"}\n"
"QCheckBox::indicator:hover{\n"
"    border-color:#0078d7; \n"
"}\n"
"QCheckBox:hover {\n"
"    color:rgb(0, 0, 216);\n"
"    padding: 3px;\n"
"}")
        self.cbx_char.setObjectName("cbx_char")
        self.verticalLayout_3.addWidget(self.cbx_char)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 20, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(GenPassword)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(GenPassword)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spb_minl = QtWidgets.QSpinBox(GenPassword)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.spb_minl.setFont(font)
        self.spb_minl.setStyleSheet("QSpinBox {\n"
"    border-style:solid;\n"
"    border-width:2px;\n"
"    border-radius:6px;\n"
"    border-color:#34495E;\n"
"    padding:1px;\n"
"    margin: 1px;\n"
"}\n"
"QSpinBox:hover{\n"
"    color:rgb(0, 0, 216);\n"
"    border-color:#0078d7;\n"
"}\n"
"QSpinBox::up-button {\n"
"    padding:1px;\n"
"    background-color:transparent;\n"
"}\n"
"QSpinBox::down-button {\n"
"    padding:1px;\n"
"    background-color:transparent;\n"
"}\n"
"QSpinBox::down-button {\n"
"    padding:1px;\n"
"    background-color:transparent;\n"
"}\n"
"/* 向上箭头*/\n"
"QSpinBox::up-arrow {\n"
"    image:url(:/mainui/icon/up1.png);\n"
"    height: 15px;\n"
"}\n"
"QSpinBox::up-arrow:hover {\n"
"    \n"
"    image: url(:/mainui/icon/up0.png);\n"
"    height: 15px;\n"
"}\n"
"QSpinBox::up-arrow:pressed {\n"
"    \n"
"    image: url(:/mainui/icon/up0.png);\n"
"    height: 13px;\n"
"}\n"
"/*向下箭头*/\n"
"QSpinBox::down-arrow {\n"
"    image: url(:/mainui/icon/down1.png);\n"
"    height: 15px;\n"
"}\n"
"QSpinBox::down-arrow:hover {\n"
"    image: url(:/mainui/icon/down0.png);\n"
"    height: 15px;\n"
"}\n"
"QSpinBox::down-arrow:pressed {\n"
"    image: url(:/mainui/icon/down0.png);\n"
"    height: 13px;\n"
"}\n"
"")
        self.spb_minl.setAlignment(QtCore.Qt.AlignCenter)
        self.spb_minl.setMaximum(256)
        self.spb_minl.setProperty("value", 6)
        self.spb_minl.setObjectName("spb_minl")
        self.gridLayout.addWidget(self.spb_minl, 0, 1, 1, 1)
        self.spb_maxl = QtWidgets.QSpinBox(GenPassword)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.spb_maxl.setFont(font)
        self.spb_maxl.setStyleSheet("QSpinBox {\n"
"    border-style:solid;\n"
"    border-width:2px;\n"
"    border-radius:6px;\n"
"    border-color:#34495E;\n"
"    padding:1px;\n"
"    margin: 1px;\n"
"}\n"
"QSpinBox:hover{\n"
"    color:rgb(0, 0, 216);\n"
"    border-color:#0078d7;\n"
"}\n"
"QSpinBox::up-button {\n"
"    padding:1px;\n"
"    background-color:transparent;\n"
"}\n"
"QSpinBox::down-button {\n"
"    padding:1px;\n"
"    background-color:transparent;\n"
"}\n"
"QSpinBox::down-button {\n"
"    padding:1px;\n"
"    background-color:transparent;\n"
"}\n"
"/* 向上箭头*/\n"
"QSpinBox::up-arrow {\n"
"    image:url(:/mainui/icon/up1.png);\n"
"    height: 15px;\n"
"}\n"
"QSpinBox::up-arrow:hover {\n"
"    \n"
"    image: url(:/mainui/icon/up0.png);\n"
"    height: 15px;\n"
"}\n"
"QSpinBox::up-arrow:pressed {\n"
"    \n"
"    image: url(:/mainui/icon/up0.png);\n"
"    height: 13px;\n"
"}\n"
"/*向下箭头*/\n"
"QSpinBox::down-arrow {\n"
"    image: url(:/mainui/icon/down1.png);\n"
"    height: 15px;\n"
"}\n"
"QSpinBox::down-arrow:hover {\n"
"    image: url(:/mainui/icon/down0.png);\n"
"    height: 15px;\n"
"}\n"
"QSpinBox::down-arrow:pressed {\n"
"    image: url(:/mainui/icon/down0.png);\n"
"    height: 13px;\n"
"}\n"
"")
        self.spb_maxl.setAlignment(QtCore.Qt.AlignCenter)
        self.spb_maxl.setMaximum(256)
        self.spb_maxl.setProperty("value", 16)
        self.spb_maxl.setObjectName("spb_maxl")
        self.gridLayout.addWidget(self.spb_maxl, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(50, 20, 50, 30)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tb_brower = QtWidgets.QTextBrowser(GenPassword)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.tb_brower.setFont(font)
        self.tb_brower.setAutoFillBackground(True)
        self.tb_brower.setStyleSheet("QTextBrowser {\n"
"    border-style:none;\n"
"    padding:3px;\n"
"    border-radius:8px;\n"
"    border:2px solid #DCE4EC;\n"
"}\n"
"QTextBrowser:hover,QTextBrowser:focus {\n"
"    border:2px solid #34495E;\n"
"}")
        self.tb_brower.setObjectName("tb_brower")
        self.verticalLayout_4.addWidget(self.tb_brower)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pbt_gen = QtWidgets.QPushButton(GenPassword)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbt_gen.setFont(font)
        self.pbt_gen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pbt_gen.setStyleSheet("QPushButton {\n"
"    border-style:none;\n"
"    padding:8px;\n"
"    border-radius:15px;\n"
"    color:#FFFFFF;\n"
"    background:#34495E;\n"
"}\n"
"QPushButton:hover {\n"
"    color:#4E6D8C;\n"
"    background:#e5e5e5;\n"
"    border:2px solid #34495E;\n"
"}\n"
"QPushButton:pressed {\n"
"    color:#000000;\n"
"    background:#B8C6D1;\n"
"}\n"
"QPushButton:disabled{\n"
"    background:rgb(134, 134, 134);\n"
"    border-color:rgb(134, 134, 134);\n"
"}\n"
"")
        self.pbt_gen.setDefault(True)
        self.pbt_gen.setObjectName("pbt_gen")
        self.horizontalLayout_2.addWidget(self.pbt_gen)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pbt_sure = QtWidgets.QPushButton(GenPassword)
        self.pbt_sure.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbt_sure.setFont(font)
        self.pbt_sure.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pbt_sure.setStyleSheet("QPushButton {\n"
"    border-style:none;\n"
"    padding:8px;\n"
"    border-radius:15px;\n"
"    color:#FFFFFF;\n"
"    background:#34495E;\n"
"}\n"
"QPushButton:hover {\n"
"    color:#4E6D8C;\n"
"    background:#e5e5e5;\n"
"    border:2px solid #34495E;\n"
"}\n"
"QPushButton:pressed {\n"
"    color:#000000;\n"
"    background:#B8C6D1;\n"
"}\n"
"QPushButton:disabled{\n"
"    background:rgb(134, 134, 134);\n"
"    border-color:rgb(134, 134, 134);\n"
"}")
        self.pbt_sure.setObjectName("pbt_sure")
        self.horizontalLayout_2.addWidget(self.pbt_sure)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)

        self.retranslateUi(GenPassword)
        QtCore.QMetaObject.connectSlotsByName(GenPassword)

    def retranslateUi(self, GenPassword):
        _translate = QtCore.QCoreApplication.translate
        GenPassword.setWindowTitle(_translate("GenPassword", "生成随机密码"))
        self.cbx_uppercase.setText(_translate("GenPassword", "大写字母"))
        self.cbx_lowercase.setText(_translate("GenPassword", "小写字母"))
        self.cbx_digital.setText(_translate("GenPassword", "数字"))
        self.cbx_char.setText(_translate("GenPassword", "特殊字符"))
        self.label_2.setText(_translate("GenPassword", "最大长度"))
        self.label.setText(_translate("GenPassword", "最小长度"))
        self.pbt_gen.setToolTip(_translate("GenPassword", "生成密码"))
        self.pbt_gen.setText(_translate("GenPassword", "生成"))
        self.pbt_gen.setShortcut(_translate("GenPassword", "Enter"))
        self.pbt_sure.setToolTip(_translate("GenPassword", "确认填写"))
        self.pbt_sure.setText(_translate("GenPassword", "确定"))


import gui.src.icons_rc
