# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\FileBox\Code\Python\PasswordManager\py-passwordmanager\gui\SigninUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Signin(object):
    def setupUi(self, Signin):
        Signin.setObjectName("Signin")
        Signin.resize(440, 360)
        Signin.setMinimumSize(QtCore.QSize(440, 360))
        Signin.setMaximumSize(QtCore.QSize(440, 360))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        Signin.setFont(font)
        self.le_pswd = QtWidgets.QLineEdit(Signin)
        self.le_pswd.setGeometry(QtCore.QRect(94, 110, 252, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.le_pswd.setFont(font)
        self.le_pswd.setStyleSheet("QLineEdit {\n"
"    border-style:none;\n"
"    padding:6px;\n"
"    border-radius:15px;\n"
"    border:2px solid #DCE4EC;\n"
"}\n"
"QLineEdit:focus {\n"
"    border:2px solid #34495E;\n"
"}\n"
"")
        self.le_pswd.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.le_pswd.setClearButtonEnabled(True)
        self.le_pswd.setObjectName("le_pswd")
        self.le_proof = QtWidgets.QLineEdit(Signin)
        self.le_proof.setGeometry(QtCore.QRect(94, 190, 252, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.le_proof.setFont(font)
        self.le_proof.setStyleSheet("QLineEdit {\n"
"    border-style:none;\n"
"    padding:6px;\n"
"    border-radius:15px;\n"
"    border:2px solid #DCE4EC;\n"
"}\n"
"QLineEdit:focus {\n"
"    border:2px solid #34495E;\n"
"}\n"
"")
        self.le_proof.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.le_proof.setClearButtonEnabled(True)
        self.le_proof.setObjectName("le_proof")
        self.label = QtWidgets.QLabel(Signin)
        self.label.setGeometry(QtCore.QRect(10, 0, 431, 101))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Signin)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 270, 421, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pbt_cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbt_cancel.setFont(font)
        self.pbt_cancel.setStyleSheet("QPushButton {\n"
"    border-style:none;\n"
"    padding:8px;\n"
"    border-radius:12px;\n"
"    color:#FFFFFF;\n"
"    background:#34495E;\n"
"    border:2px solid #34495E;\n"
"}\n"
"QPushButton:hover {\n"
"    color:#4E6D8C;\n"
"    background:#F0F0F0;\n"
"}\n"
"QPushButton:pressed {\n"
"    color:#2D3E50;\n"
"    background:#B8C6D1;\n"
"}\n"
"")
        self.pbt_cancel.setObjectName("pbt_cancel")
        self.horizontalLayout.addWidget(self.pbt_cancel)
        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pbt_setting = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbt_setting.setFont(font)
        self.pbt_setting.setStyleSheet("QPushButton {\n"
"    border-style:none;\n"
"    padding:8px;\n"
"    border-radius:12px;\n"
"    color:#FFFFFF;\n"
"    background:#34495E;\n"
"    border:2px solid #34495E;\n"
"}\n"
"QPushButton:hover {\n"
"    color:#4E6D8C;\n"
"    background:#F0F0F0;\n"
"}\n"
"QPushButton:pressed {\n"
"    color:#2D3E50;\n"
"    background:#B8C6D1;\n"
"}\n"
"QPushButton:disabled{\n"
"    background:rgb(134, 134, 134)\n"
"}\n"
"")
        self.pbt_setting.setObjectName("pbt_setting")
        self.horizontalLayout.addWidget(self.pbt_setting)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.warning = QtWidgets.QPushButton(Signin)
        self.warning.setGeometry(QtCore.QRect(90, 240, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        self.warning.setFont(font)
        self.warning.setStyleSheet("color:red;")
        self.warning.setFlat(True)
        self.warning.setObjectName("warning")

        self.retranslateUi(Signin)
        QtCore.QMetaObject.connectSlotsByName(Signin)

    def retranslateUi(self, Signin):
        _translate = QtCore.QCoreApplication.translate
        Signin.setWindowTitle(_translate("Signin", "设置管理员密码"))
        self.label.setText(_translate("Signin", "设置管理员密码，用于进入此应用；\n"
"每个计算机用户仅允许一个管理员存在;.\n"
"密码长度为6~256，可包含字母、数字、符号（@ . # $）"))
        self.pbt_cancel.setText(_translate("Signin", "取消"))
        self.pbt_setting.setText(_translate("Signin", "设置"))
        self.warning.setText(_translate("Signin", "密码不一致！"))
