# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\FileBox\Code\Python\PasswordManager\py-passwordmanager\gui\SettingUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settingDialog(object):
    def setupUi(self, settingDialog):
        settingDialog.setObjectName("settingDialog")
        settingDialog.resize(472, 510)
        settingDialog.setMinimumSize(QtCore.QSize(390, 390))
        settingDialog.setMaximumSize(QtCore.QSize(600, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mainui/icon/MainIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        settingDialog.setWindowIcon(icon)
        settingDialog.setStyleSheet("QScrollArea {\n"
"    border:none;\n"
"    background:white;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    padding: 2px;margin: 2px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:2px;\n"
"    border-color:#34495E;\n"
"      background-color:rgb(255,255,255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:2px;\n"
"    border-color:#0078d7; \n"
"    image: url(:/mainui/icon/selected.png);\n"
"}\n"
"QCheckBox::indicator:hover{\n"
"    border-color:#0078d7; \n"
"}\n"
"QCheckBox:hover {\n"
"    color:rgb(0, 0, 216);\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-style:none;\n"
"    padding:7px;\n"
"    border-radius:15px;\n"
"    color:#FFFFFF;\n"
"    background:#34495E;\n"
"}\n"
"QPushButton:hover {\n"
"    color:#4E6D8C;\n"
"    background:#e5e5e5;\n"
"    border:2px solid #34495E;\n"
"}\n"
"QPushButton:pressed {\n"
"    color:#000000;\n"
"    background:#B8C6D1;\n"
"}\n"
"\n"
"/*表右侧的滑条*/\n"
"QScrollBar:vertical {\n"
"    background:#484848;\n"
"    padding:0px;\n"
"    border-radius:6px;\n"
"    max-width:12px;\n"
"}\n"
"\n"
"/*滑块*/\n"
"QScrollBar::handle:vertical {\n"
"    background:#CCCCCC;\n"
"}\n"
"/*\n"
"滑块悬浮，按下*/\n"
"QScrollBar::handle:hover:vertical,QScrollBar::handle:pressed:vertical {\n"
"    background:#A7A7A7;\n"
"}\n"
"/*\n"
"滑块已经划过的区域*/\n"
"QScrollBar::sub-page:vertical {\n"
"    background:444444;\n"
"}\n"
"\n"
"/*\n"
"滑块还没有划过的区域*/\n"
"QScrollBar::add-page:vertical {\n"
"    background:5B5B5B;\n"
"}\n"
"\n"
"/*页面下移的按钮*/\n"
"QScrollBar::add-line:vertical {\n"
"    background:none;\n"
"}\n"
"/*页面上移的按钮*/\n"
"QScrollBar::sub-line:vertical {\n"
"    background:none;\n"
"}\n"
"\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(settingDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(settingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet("\n"
"background-color:white;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 454, 414))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sb_autoLockTime = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.sb_autoLockTime.setFont(font)
        self.sb_autoLockTime.setStyleSheet("QSpinBox {\n"
"    border-style:solid;\n"
"    border-width:2px;\n"
"    border-radius:6px;\n"
"    border-color:#34495E;\n"
"    padding:1px;\n"
"    margin: 1px;\n"
"}\n"
"QSpinBox:hover{\n"
"    color:rgb(0, 0, 216);\n"
"    border-color:#0078d7;\n"
"}\n"
"QSpinBox::up-button {\n"
"    padding:1px;\n"
"    background-color:transparent;\n"
"}\n"
"QSpinBox::down-button {\n"
"    padding:1px;\n"
"    background-color:transparent;\n"
"}\n"
"QSpinBox::down-button {\n"
"    padding:1px;\n"
"    background-color:transparent;\n"
"}\n"
"/* 向上箭头*/\n"
"QSpinBox::up-arrow {\n"
"    image:url(:/mainui/icon/up1.png);\n"
"    height: 15px;\n"
"}\n"
"QSpinBox::up-arrow:hover {\n"
"    \n"
"    image: url(:/mainui/icon/up0.png);\n"
"    height: 15px;\n"
"}\n"
"QSpinBox::up-arrow:pressed {\n"
"    \n"
"    image: url(:/mainui/icon/up0.png);\n"
"    height: 13px;\n"
"}\n"
"/*向下箭头*/\n"
"QSpinBox::down-arrow {\n"
"    image: url(:/mainui/icon/down1.png);\n"
"    height: 15px;\n"
"}\n"
"QSpinBox::down-arrow:hover {\n"
"    image: url(:/mainui/icon/down0.png);\n"
"    height: 15px;\n"
"}\n"
"QSpinBox::down-arrow:pressed {\n"
"    image: url(:/mainui/icon/down0.png);\n"
"    height: 13px;\n"
"}\n"
"")
        self.sb_autoLockTime.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_autoLockTime.setObjectName("sb_autoLockTime")
        self.horizontalLayout.addWidget(self.sb_autoLockTime)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 336))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cb_autoBackup = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.cb_autoBackup.setFont(font)
        self.cb_autoBackup.setObjectName("cb_autoBackup")
        self.gridLayout_2.addWidget(self.cb_autoBackup, 4, 1, 1, 1)
        self.cb_deleteTips = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.cb_deleteTips.setFont(font)
        self.cb_deleteTips.setObjectName("cb_deleteTips")
        self.gridLayout_2.addWidget(self.cb_deleteTips, 2, 1, 1, 1)
        self.cb_showToolTips = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.cb_showToolTips.setFont(font)
        self.cb_showToolTips.setObjectName("cb_showToolTips")
        self.gridLayout_2.addWidget(self.cb_showToolTips, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        self.cb_pushCtrl = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.cb_pushCtrl.setFont(font)
        self.cb_pushCtrl.setObjectName("cb_pushCtrl")
        self.gridLayout_2.addWidget(self.cb_pushCtrl, 5, 1, 1, 1)
        self.cb_showLineIndex = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.cb_showLineIndex.setFont(font)
        self.cb_showLineIndex.setObjectName("cb_showLineIndex")
        self.gridLayout_2.addWidget(self.cb_showLineIndex, 1, 1, 1, 1)
        self.cb_useRegExpSearch = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.cb_useRegExpSearch.setFont(font)
        self.cb_useRegExpSearch.setObjectName("cb_useRegExpSearch")
        self.gridLayout_2.addWidget(self.cb_useRegExpSearch, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 2, 1, 1)
        self.cb_mouseClickSelect = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.cb_mouseClickSelect.setFont(font)
        self.cb_mouseClickSelect.setObjectName("cb_mouseClickSelect")
        self.gridLayout_2.addWidget(self.cb_mouseClickSelect, 6, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.pbt_cancel = QtWidgets.QPushButton(settingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbt_cancel.sizePolicy().hasHeightForWidth())
        self.pbt_cancel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbt_cancel.setFont(font)
        self.pbt_cancel.setObjectName("pbt_cancel")
        self.horizontalLayout_4.addWidget(self.pbt_cancel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.pbt_save = QtWidgets.QPushButton(settingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbt_save.sizePolicy().hasHeightForWidth())
        self.pbt_save.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbt_save.setFont(font)
        self.pbt_save.setObjectName("pbt_save")
        self.horizontalLayout_4.addWidget(self.pbt_save)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem7, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem8, 3, 0, 1, 1)

        self.retranslateUi(settingDialog)
        QtCore.QMetaObject.connectSlotsByName(settingDialog)

    def retranslateUi(self, settingDialog):
        _translate = QtCore.QCoreApplication.translate
        settingDialog.setWindowTitle(_translate("settingDialog", "设置"))
        self.label.setText(_translate("settingDialog", "无动作自动锁定时间(分)"))
        self.cb_autoBackup.setText(_translate("settingDialog", "自动备份"))
        self.cb_deleteTips.setText(_translate("settingDialog", "删除时确认提示"))
        self.cb_showToolTips.setText(_translate("settingDialog", "显示tooltips"))
        self.cb_pushCtrl.setText(_translate("settingDialog", "按住Ctrl键显示密码"))
        self.cb_showLineIndex.setText(_translate("settingDialog", "显示行号"))
        self.cb_useRegExpSearch.setText(_translate("settingDialog", "使用正则表达式搜索"))
        self.cb_mouseClickSelect.setText(_translate("settingDialog", "鼠标单击选中行"))
        self.pbt_cancel.setText(_translate("settingDialog", "取消"))
        self.pbt_save.setText(_translate("settingDialog", "保存"))
import gui.src.icons_rc
